language: go

go:
  - '1.9' # This uses automatically the latest version of go

install:
  - sudo dpkg -i hugo*.deb # This provides the latest version of Hugo to $

script:
  - hugo # This commands builds your website on travis


deploy:
  #edge:
  local_dir: public # Default static site output dir for Hugo
  repo: manjoong/manjoong.github.io # This is the slug of the repo you want to deploy your $
  target_branch: master # GitHub pages branch to deploy to (in other cases it$
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # This is the authentication which you will setup$
  keep-history: true
  email: skekf123@naver.com
  fqdn: manjoong.github.io
  name: "manjoong"
  on:
    branch: master
