baseURL = "https://skcloud.github.io/zaction"

languageCode = "en-us"
title = "Cloud Z"
theme = "hugo-theme-learn"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = "false"
hasCJKLanguage = "true"
paginate = "5"
[permalinks]
  post = "/:year/:month/:title/"

defaultContentLanguage = "ko"
